
[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraMono Nerd Font Mono"
style = "Medium"

[font.bold_italic]
family = " FiraMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FireMono Nerd Font Mono"
style = "Medium"

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
