[General]
height=1418
width=1280
x=1280
y=0

[Browser]
autoPlayPreviews=true
dirConf=true
gridSize=3
lastSession=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\t\0\0\0\x1\0\0\0\b\0\0\0\x1\0\0\0\b\0p\0\x61\0t\0h\0\0\0\n\0\0\0\x64\0\x66\0i\0l\0\x65\0:\0/\0/\0/\0h\0o\0m\0\x65\0/\0v\0\x61\0l\0/\0.\0\x64\0o\0t\0\x66\0i\0l\0\x65\0s\0/\0\x63\0o\0n\0\x66\0i\0g\0/\0s\0p\0i\0\x63\0\x65\0t\0i\0\x66\0y\0/\0T\0h\0\x65\0m\0\x65\0s)
lastTabIndex=0
listSize=0
overviewStart=false
previewFiles=false
previewerWindow=true
quickSidebarSection=true
restoreSession=false
showHiddenFiles=true
showThumbnails=true
sideBarWidth=200
sidebarSections=13, 1, 3, 2
syncTerminal=true
terminalColorScheme=Maui-Dark
terminalFollowsColorScheme=true
viewType=1

[Sorting]
foldersFirst=true
group=false
sortBy=11
sortOrder=0
